# Generated by Django 4.2.1 on 2023-07-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_persontocontact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('fullname_kz', models.CharField(max_length=300)),
                ('fullname_ru', models.CharField(max_length=300)),
                ('fullname_en', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_kz', models.CharField(max_length=100)),
                ('first_name_ru', models.CharField(max_length=100)),
                ('first_name_en', models.CharField(max_length=100)),
                ('last_name_kz', models.CharField(max_length=100)),
                ('last_name_ru', models.CharField(max_length=100)),
                ('last_name_en', models.CharField(max_length=100)),
                ('patronymic_kz', models.CharField(max_length=100)),
                ('patronymic_ru', models.CharField(max_length=100)),
                ('patronymic_en', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('origin_name', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(max_length=100)),
                ('name_kz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=200)),
                ('name_kz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('begin_year', models.DateField()),
                ('end_year', models.DateField()),
                ('cmt_kz', models.CharField(max_length=200)),
                ('cmt_ru', models.CharField(max_length=200)),
                ('cmt_en', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.customer')),
                ('head_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(max_length=200)),
                ('name_kz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('lang', models.CharField(max_length=100)),
                ('d_year', models.DateField()),
                ('cmt_kz', models.CharField(max_length=200)),
                ('cmt_ru', models.CharField(max_length=200)),
                ('cmt_en', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=200)),
                ('research_type', models.CharField(max_length=200)),
                ('name_kz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('cmt_kz', models.CharField(max_length=200)),
                ('cmt_ru', models.CharField(max_length=200)),
                ('cmt_en', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=200)),
                ('name_kz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('cmt_kz', models.CharField(max_length=200)),
                ('cmt_ru', models.CharField(max_length=200)),
                ('cmt_en', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=200)),
                ('solution_type', models.CharField(max_length=200)),
                ('name_kz', models.CharField(max_length=200)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('cmt_kz', models.CharField(max_length=200)),
                ('cmt_ru', models.CharField(max_length=200)),
                ('cmt_en', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=200)),
                ('file_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.filestorage')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.solution')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=200)),
                ('file_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.filestorage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.publication')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.research')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.filestorage')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.publication')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.employee')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.publication')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.service')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.solution')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=200)),
                ('file_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.filestorage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbeg', models.DateField()),
                ('dend', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.position')),
            ],
        ),
    ]
